# ncc_list=["LEGAL (2C)",'LÒ SẤY 2.4 CHÚ BÉ (ABC)',
# 'AN CƯỜNG',
# 'BẢO HƯNG (2C)',
# 'GỖ LAM (ABC)',
# 'CHÂU MỸ (2C)',
# 'MỘC BẢO GIA (BC)',
# 'LÒ SẤY 2.3 CHÚ BÉ (ABC)',
# 'LÒ SẤY 2.2 CHÚ BÉ (ABC)',
# 'LÒ SẤY 2.7 CHÚ BÉ (ABC)',
# 'LÒ SẤY 2.2 TÂN THÀNH',
# 'LÒ SẤY 2.9 XUÂN TRUNG (ABC)',
# 'LÒ SẤY 2.7 CHÚ BÉ  (ABC).',
# 'LÒ SẤY 2.8 TÂN THÀNH (ABC)',
# 'LÒ SẤY 2.8 XUÂN TRUNG (ABC)',
# 'MỘC BẢO GIA (ABC)',
# 'PHƯƠNG ĐÔNG (AB)',
# 'S-WOOD (2C)',
# 'TẤN TÀI ',
# 'ĐÀO BÁCH',
# 'AG WOOD GMBH (AA)',
# 'AG WOOD GMBH (ABC)']

go_list=["ALDER",
"ASH VN",
"ASH",
"BẠCH ĐÀN",
"BEECH",
"CĂM XE",
"CAO SU ĐEN",
"CAO SU",
"CHERRY",
"CHÒ CHỈ",
"SYCAMORE",
"DỪA",
"DƯƠNG LIỄU",
"GÒN",
"HICKORY",
"KAPUS",
"LÒNG MỨT",
"MAPLE",
"MÍT",
"MUỒNG",
"NEP PALLET",
"OAK",
"PƠ MU",
"POPLAR",
"RED ELM",
"RED OAK",
"SỌ KHỈ",
"TẠP",
"TEAK",
"THÔNG",
"TRÀM",
"TRÅU",
"WALNUT",
"WHITE OAK",
"WHITE POPLAR",
"WILLOW",
"XOÀI"
]


qc_list=['Tuấn','Mứt','Trúc']
